### ISSUE TITLE
Bulk Setup of Entities

### ISSUE THREAD

**Issue by briandowns** [dimiro1/health#11]
Have you given any thought to having the ability to do a bulk import / setup of entities to check?  Just curious.
ie 

```json
{
    "websites": {
        "type": { 
                "http": [
                    "http://golang.org",
                    "http://google.com",
                    "http://facebook.com",
                    "http://twitter.com",
                ]
            }
        },
    "databases": {
        "type": {
            "mysql": [
               "path.to.host1.local",
               "path.to.host2.local",
            ]
        }
    },
    "services": {
        "type": {
            "tcp": [
               "path.to.host1.loca:10009l",
               "path.to.host2.local:8888",
            ]
        }
    }
}
```
Or something even simpler. 

Or even the ability to give the system a handler that expects a type for POST'ing in new data to look for?

BTW, I love this library.  Great work.  I can't wait to start using it.

**Comment by dimiro1** [comment]
I never thought about it, but I think it is a good Idea. To implement this I think The system need some kind of register to know what Check it have to instantiate.

**Comment by briandowns** [comment]
I can probably throw something together for a base to work from if you're interested.

**Comment by dimiro1** [comment]
@briandowns Sure, thank you.

**Comment by briandowns** [comment]
Something like #12 .  All feedback is welcome.  It's not complete but the base to get some ideas going.
