### ISSUE TITLE
Parallel checks

### ISSUE THREAD

**Issue by dimiro1** [dimiro1/health#20]
Right now the checks are executed one after another, would be interesting to execute them in parallel.

See: https://github.com/dimiro1/health/blob/master/checker.go#L50

**Comment by Freakin** [comment]
It would be great to see the checks executed in scheduled goroutines, so longer-running checks aren't executed on every GET.

**Comment by mschneider82** [comment]
i have implemented @dimiro1 idea in my pull request

i also have implemented @Freakin idea in my feature branch, which adds a new Start(interval) and Stop() function to composite checker: 

https://github.com/mschneider82/health/tree/feature-background-checks
