### ISSUE TITLE
How to integrate with golang/Gin framework

### ISSUE THREAD

**Issue by bsandy999** [dimiro1/health#28]
Hello ,
     This is pretty much simple and easy to understand the script. But I am using the Golang GIN framework for my microservices. 
Where I have a configuration file and some different Redis servers for which I need a simple health check service for Redis connection. Do you have any sample examples for the same? It will be really helpful to me if i get a custom example that explains how to use this lib in Gin Framework.

**Comment by dhiemaz** [comment]
I think sample in readme is pretty straightforward, it can be used with Gin also.

**Comment by bilalcaliskan** [comment]
@dhiemaz i have worked on it more than hour but i could not succeed. do you have a living example?

**Comment by dimiro1** [comment]
@bilalcaliskan 

```go
	handler := health.NewHandler()
	handler.AddChecker("Go", url.NewCheckerWithTimeout("https://golang.org/", 5 * time.Second))

	r := gin.Default()
	r.GET("/health/", gin.WrapF(handler))
	r.Run() // listen and serve on 0.0.0.0:8080 (for windows "localhost:8080")
```

**Comment by bilalcaliskan** [comment]
@dimiro1 that is a good example, thanks for that!
