### ISSUE TITLE
Give Status its own type

### ISSUE THREAD

**Issue by bestform** [dimiro1/health#6]
Hey,

this is more of a suggestion than an issue. I think it would be helpful, to define a type for the Status property of the Health struct. This way, you can automatically check, if a checker returned an up or down state.

Currently it is checked by comparing the value of Status to "up" or "down" (strings). A custom checker does not have to use those strings. So a custom checker may say "online" and it would return false on IsUp().

This is a minor detail and you probably won't run into it, as checkers usually will use the Up() and Down() methods to alter the state of the Health struct. But in my opinion it would be cleaner to use a custom type and consts. Like

```go
type HealthStatus int

const (
	UP HealthStatus = iota
	DOWN
	OUT_OF_SERVICE
	UNKNOWN
)

type Health struct {
	Status HealthStatus 
	Info   map[string]interface{}
}
```

**Comment by dimiro1** [comment]
I understand but I have a few questions.

1. How can we get the name of the Status while rendering the json?
2. The HealthStatus type must implement something like IsUp() or IsDown() right?
3. Can you think a situation where a custom status would be a good fit?

Thank you for your time.

**Comment by bestform** [comment]
> How can we get the name of the Status while rendering the json?
You can implement the Stringer interface for your HealthStatus type. Go will use this when marshalling. So your String() method on HealthStatus can include a switch on the value and return the desired string.

> The HealthStatus type must implement something like IsUp() or IsDown() right?
No, this can still be done by your Health struct. The current methods just need to compare to the new consts.

> Can you think a situation where a custom status would be a good fit?
Well, there may be situations where you might want to add a status, but this would broaden the scope of the library, and i think, a special purpose is an advantage one should not give up.
You already have the Info property, which can hold arbitrary information, so if you really need to, you can still embed all kinds of status information in there. But the service should at least fit the up/down/oos/unknown categories to be a fit for this lib.

All of this of course is only my opinion. :)

**Comment by dimiro1** [comment]
> No, this can still be done by your Health struct. The current methods just need to compare to the new consts.

Ok but what about the custom Status implemented by the user? If comparison continues in the Health struct how can the app knows if for example a 'Online' is a Up status? 

> Well, there may be situations where you might want to add a status, but this would broaden the scope of the library, and i think, a special purpose is an advantage one should not give up.
You already have the Info property, which can hold arbitrary information, so if you really need to, you can still embed all kinds of status information in there. But the service should at least fit the up/down/oos/unknown categories to be a fit for this lib.

I appreciate your opinion :)

**Comment by bestform** [comment]
> Ok but what about the custom Status implemented by the user? If comparison continues in the Health struct how can the app knows if for example a 'Online' is a Up status?

The idea behind the separate type and the consts as values is to avoid this situation. A user should not define her own status, so your code is able to determine, if a service is up or not just by looking at its value, which will always be one of UP/DOWN/OUT_OF_SERVICE/UNKNOWN

Of course a user COULD in theory define her own value here, but the use of those consts and the type indicates, that she probably shouldn't. That's not the case if you are just using strings.

**Comment by dimiro1** [comment]
> The idea behind the separate type and the consts as values is to avoid this situation. A user should not define her own status, so your code is able to determine, if a service is up or not just by looking at its value, which will always be one of UP/DOWN/OUT_OF_SERVICE/UNKNOWN

Understand, now I see your point. It makes sense to me now. Do you want to contribute with this change?

**Comment by bestform** [comment]
Sure, I'll send a pull request as soon as I find some time.

**Comment by dimiro1** [comment]
@bestform Another thing that could be done is not export the Status member on the Health struct.

**Comment by bestform** [comment]
Yeah, but then it would not be in the json, or would it?

**Comment by dimiro1** [comment]
@bestform Yes, but the Health struct already have a MarshalJSON method.

https://github.com/dimiro1/health/blob/master/health.go#L26

**Comment by bestform** [comment]
oh, i see. yeah, that makes sense

**Comment by dimiro1** [comment]
@bestform  If you are ok with this approach, I can implement this right now.

**Comment by bestform** [comment]
There we go. status is not being exported in this PR as well.

**Comment by dimiro1** [comment]
@bestform merged your PR.

**Comment by bestform** [comment]
great. Thanks. :)
