### ISSUE TITLE
Using HEAD over GET in request

### ISSUE THREAD

**Issue by sno6** [dimiro1/health#8]
Hello,

Would it be a better option to use a HTTP HEAD request instead of a GET request for the occasion where MANY urls are needed to be pinged for status information.

This may be a quicker alternative to getting the whole document body.

https://github.com/dimiro1/health/blob/master/url/checker.go#l23

**Comment by dimiro1** [comment]
Thank you @sno6 I implemented on the commit https://github.com/dimiro1/health/commit/2305be1e94a30e5d3e83ecf46a6f3fb065323750
