### ISSUE TITLE
Me Info its own sub node when marshaling

### ISSUE THREAD

**Issue by bestform** [dimiro1/health#9]
Currently all keys of the Info map are marshaled on the same level as the status. So if someone adds a "status" entry to the Info map, it will overwrite the actual status.

Maybe this is intentional but I see a great danger here that a custom checker will alter the json in an unintentional way.

**Comment by dimiro1** [comment]
@bestform it was intentional, but you are right.

The reason was I wanted a simple json, before that I was rendering the Json as:

```json
{
    "status": "UP",
    "info": {
    }
}
```

Every check had this info key on the json, it just looked ugly with a very nested check tree.

What is your suggestion?

**Comment by bestform** [comment]
This could be handled by the MarshalJSON method. if the map is empty, it can just avoid marshaling it at all.

**Comment by dimiro1** [comment]
@bestform I think it is a very good solution, but it have to be documented in the Readme file. Do you want to contribute with this change?

**Comment by bestform** [comment]
Sure, but I cannot guarantee that I'll get it done by tonight.

**Comment by dimiro1** [comment]
@bestform Fine, I will keep the Issue open. Thank you.

**Comment by bestform** [comment]
Hmm, this clashes with the concept of the CompositeChecker, which currently saves all checkers in its Info map. 

But converting this into a format that shows every checker's result in its info node does make sense in my opinion. So I've also altered the expectation in the corresponding test.

On that note: kudos to you for writing tests. I probably wouldn't have seen this issue without your tests. Way to go :)

**Comment by dimiro1** [comment]
Fixed in https://github.com/dimiro1/health/commit/68671c53fef441bd953e542ca449df7863ed111d
